### ISSUE TITLE
Search doesn't seem to be taking excerpts into account

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-plugins-website#15]
It looks like search results don't take content of excerpts into account when providing results - @bloke is this something obvious I've overlooked? Always though searches looked at excerpt *and* body content as a default?

**Comment by bloatware** [comment]
@philwareham it depends on `searchable_article_fields` pref that defaults to `Title, Body`.

**Comment by philwareham** [comment]
Thanks. Is that a hidden pref? How do I change it?

**Comment by bloatware** [comment]
Changing it does not suffice, you have to rebuild a fulltext db index. IIRC, Robert has a plugin for this ([wet_haystack](https://awasteofwords.com/software/wet_haystack-textpattern-plugin)).

**Comment by philwareham** [comment]
Great! Thanks Oleg. I've run that plugin on the site and then removed it - excerpts are now treated as part of the searchable content.
