### ISSUE TITLE
Display a message when no plugins currently exist in a category

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-plugins-website#16]
Note to self: I haven't built in logic yet to display a message when a user filters by category and no actual plugins are available in that category yet. Should fix for nicer UX.

**Comment by Bloke** [comment]
Note to you at the same time: tweak the wording in the search_results form to say: 1 plugin(s) found matching your search request "{term}". Unless we're thinking of using the site to add articles in future? Maybe link juice articles about what plugins go well together, or which ones are useful for particular types of site?

**Comment by philwareham** [comment]
Done, and also the search results text amend done.
