### ISSUE TITLE
expand searches

### ISSUE THREAD

**Issue by colak** [textpattern/textpattern-plugins-website#17]
**Describe the issue**
When searching for plugins compatible to a particular txp version, no results are returned after making a selection from the pulldown but text field is empty. 

**To reproduce**
Steps to reproduce the behaviour:
1. Go to homepage
2. Click on the txp version pulldown and select one of them (leave search field empty)
3. Click search

**Expected behaviour**
A list of version specific plugins

**Comment by philwareham** [comment]
@bloke @bloatware is this achievable and OK to do? Default Textpattern behaviour is to not do a search when the search field is empty - we would need to change that behaviour here to show everything if the field is empty (and filter by custom fields, which we do in the results anyway).

**Comment by Bloke** [comment]
`<txp:if_search>` will fail if `q=` is empty but this code will pass the test:

```
<txp:if_request type="request" name="q">
   YEP, haz request: <txp:page_url type="q" />
</txp:if_request>
```

So we could perhaps replace `<txp:if_search>` for the above and then deal with situations where `q` is empty slightly differently.

**Comment by bloatware** [comment]
`<txp:if_article_list type="q, compatibility" />` should work for search detection, but `<txp:if_search_results />` and the likes require `q`.

**Comment by philwareham** [comment]
Sorry, I don't understand either of those two solutions - can somebody please amend the page code, which I guess starts around here: https://github.com/textpattern/textpattern-plugins-website/blob/master/src/templates/pages/default.txp#L106

Thanks.

**Comment by bloatware** [comment]
It should work now, please test.

**Comment by Bloke** [comment]
It works on the site but I can't see any change in the repo. Did you just change it directly on the site?

One thing we might be able to do in the search message at the top is add the compatibility info requested if it's anything other than 'any'. e.g.

N plugin(s) found<txp:if_variable name="compatibility" not value="Any"> compatible with Textpattern <txp:variable name="compatibility" /></txp:if_variable> matching your search request "any".

Would that work?

**Comment by bloatware** [comment]
Oops! Sorry, I have changed the site directly. Yes, `evaluate` would work (even without `test`), or you could also use
```
<txp:search_term wraptag="matching your search request <q><+></q>" />
```

**Comment by Bloke** [comment]
Even better. I always forget about `<+>`.

**Comment by bloatware** [comment]
For the record, I have modified only `default` page.

**Comment by Bloke** [comment]
Oki doke. If you're done tinkering for now, I'll commit your changes to the repo.

**Comment by Bloke** [comment]
Can anyone unravel what's going on here?

* Search for `etc_` with 'Any compatibility: 3 plugins returned.
  etc_pagination (4.5-4.8)
  etc_cache (4.6-4.8)
  etc_datepicker (4.6-4.8).
* Same search but select Compatibility 4.8: 2 plugins found. etc_pagination is missing but it's compatible with 4.8.
* Same search but select Compatibility 4.5: No plugins found. etc_pagination is missing but it's compatible with 4.5.

Is it because there's no `max-txp-version-verified` for etc_pagination?

**Comment by philwareham** [comment]
Yes the search is for verified plugins, because that plugin hasn’t been verified yet it won’t show in search results. It’s the best I could do - not precious about it though, if you can improve it that’d be fine with me.

**Comment by philwareham** [comment]
Just looking at the code additions, curious about what this does?...

    <txp:output_form yield="head, body_header, body_footer" />

**Comment by bloatware** [comment]
@philwareham preloads and caches these forms in one go, sparing 2 further db queries. Useless if queries are cached by db engine, in which case it's safe to remove.

**Comment by bloatware** [comment]
@Bloke @philwareham sorry, I have slightly modified `default` page of the site again (too lazy to setup my local copy). Just removed two `pgonly` queries, replacing them with `variable` store.

**Comment by philwareham** [comment]
Done. Closing.
