### ISSUE TITLE
Sunsetting of textpattern.org

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-plugins-website#22]
WIP catch-all for the eventual decommissioning of textpattern.org.

- [ ] map .org URLs to plugins site
- [ ] notify active plugin authors about change of URL and process

**Comment by jools-r** [comment]
Got the email notification but not the closure notice so apologies for posting to a now closed topic. If it's any help I have the following URL list you could use for redirection. We have only a fraction of the plugins on the new site – to be expected as many are defunct or no longer needed. On top of that many newer plugins on the new site were never on textpattern.org, so the overlap is comparatively small.

Here's an excel file with the matching plugin urls as well as the corresponding plugin category links:

- [textpattern-plugins-old-new_urls.xlsx](https://github.com/textpattern/textpattern-plugins-website/files/15291459/textpattern-plugins-old-new_urls.xlsx)

You should be able to construct an nginx redirect file from these. The `/category/{category-name}` and `/categoryarchive/?c={category-name}` source urls you can probably handle together via a regex.

For info, these are the current full plugin and category url lists for textpattern.org:

- [textpattern-org_urls_plugins.txt](https://github.com/textpattern/textpattern-plugins-website/files/15291499/textpattern-org_urls_plugins.txt)
- [textpattern-org_urls_plugin-categories.txt](https://github.com/textpattern/textpattern-plugins-website/files/15291500/textpattern-org_urls_plugin-categories.txt)
- [textpattern-org_urls_plugin-categoryarchives.txt](https://github.com/textpattern/textpattern-plugins-website/files/15291501/textpattern-org_urls_plugin-categoryarchives.txt)

And these are the full plugin and category url lists for plugins.textpattern.com:

- [textpattern-plugins_urls_plugins.txt](https://github.com/textpattern/textpattern-plugins-website/files/15291505/textpattern-plugins_urls_plugins.txt)
- [textpattern-plugins-urls_categories.txt](https://github.com/textpattern/textpattern-plugins-website/files/15291504/textpattern-plugins-urls_categories.txt)

**Comment by petecooper** [comment]
Thanks @jools-r – closing was for my own sanity as we're not at the stage where plugins & themes sites are in 'full fat' mode, so it's just noise in the meantime. When the plugins site is properly out of beta we can revisit.
